### PR TITLE
Animationpart2

### PR DESCRIPTION
**Pull request by tvleest**
There's still a lot to improve
Also we need te make some more tests
But should be good to merge for now

### CODE REVIEW

**Comment by jzoon** [comment]
Ziet er erg goed uit, stuk beter dan eerst. Mag van mij gemerged worden

**Comment by TimYuenior** [comment]
Looks good, but is the check on line 124 of GameLogic needed? And actually, is the combinationsFormed boolean needed at all? It is put on true and falsewithout further usage I think. Other than that, great work!

**Comment by tvleest** [comment]
Yeh its needed, if there is no combination formed, the two gems should swap back, where if a combination is formed, they should.

**Comment by TimYuenior** [comment]
I get that, but the check is in a block that is only accessible when there are no combinations formed. At least, that's what I get from line 120.

**Comment by tvleest** [comment]
It's because it loops multiple times, try removing it and you'll see why its needed.

**Comment by TimYuenior** [comment]
Ah, I see, you're right.The boolean prevents swapping when a combination has been formed. I get it now. Then everything is fine as it is for me.

**Pull request merged**
