### PR TITLE
Buttons

### PR DESCRIPTION
**Pull request by TimYuenior**
Added: continue button and save button.
Problem: Save button doesn't work. I tried to test it with a System.out.println("test") on ActionEvent, but it just won't respond. (line 192)
Implementation looks similar to other buttons's. Can you see something off?
I put a File declaration at the top to be able to simulate the if condition on line 123. This is open to change when the loading gets linked.

### CODE REVIEW

**Comment by tvleest** [comment]
Probably best to wait with a merge till it works, i'll take a look

**Comment by tvleest** [comment]
You should probably put the button in the gamescene instead of the MainClass.

**Comment by TimYuenior** [comment]
That was indeed the way to fix the problem!
The savebutton is now fixed (still no actual functionality though) and the buttons will be darker when hovering over it.
Also, a static default button maker class was made to reduce  the number of lines needed to create them.

**Comment by tvleest** [comment]
Button class seems like a good improvement!

**Comment by TimYuenior** [comment]
Alright, I'll merge it.

**Pull request merged**
